GET http://localhost:4000/test

###

POST http://localhost:4000
Content-Type: application/json

{
    "name": "Mushfique",
    "countrty": "BD",
    "rank": 3
}

###

GET http://localhost:4000

###

GET http://localhost:4000/3ukW80PEH