//health check of this website
GET http://localhost:4000/test

###

// Create a player
POST http://localhost:4000
Content-Type: application/json

{
    "name": "Mushfique",
    "countrty": "BD",
    "rank": 3
}

###

// Get all player
GET http://localhost:4000

###

// Get a single player by id
GET http://localhost:4000/3ukW80PEH

###

// Update player information
PATCH  http://localhost:4000/iy9b1i844
Content-Type: application/json

{
    "name": "Mashrafi bin Mortuza"
}

###

PUT http://localhost:4000/iy9b1i844
Content-Type: application/json

{
    "name": "mashrafi",
    "countrty": "BD",
    "rank": 20
}


###

// if playe exist in system, update player information or create a new player
PUT http://localhost:4000/iy9b1i8
Content-Type: application/json

{
    "name": "Sakib",
    "countrty": "BD",
    "rank": 1
}


###

// delete a player single player
DELETE http://localhost:4000/3ukW80PEH
